# codecov.yml
# Code coverage configuration for Fig

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: 70%
        threshold: 5%
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 5%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

ignore:
  - "Fig/Tests/**/*"
  - "**/*+Preview.swift"
  - "**/Generated/**"
  - "**/*.generated.swift"

flags:
  unittests:
    paths:
      - Fig/Sources/
    carryforward: true

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
